sudo: required
dist: trusty
language: java

cache:
  directories:
    - $HOME/.m2

#before_install:
  #- wget http://ftp.wayne.edu/apache/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip
  #- unzip -qq apache-maven-3.3.9-bin.zip
  #- export M2_HOME=$PWD/apache-maven-3.3.9
  #- export PATH=$M2_HOME/bin:$PATH
  #- export MAVEN_OPTS='-Xmx2g'

#addons:
  #apt:
    #packages:
      #- oracle-java8-installer # install newest JDK8

jdk:
  - oraclejdk8
  - openjdk8
